name: "MERGE SUBSCRIPTION"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php index.php
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "🚀 Merged Successfully - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
